//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandedMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LandedMVC.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. The email was not sent..
        /// </summary>
        public static string FormContactError {
            get {
                return ResourceManager.GetString("FormContactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string FormContactMessage {
            get {
                return ResourceManager.GetString("FormContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string FormContactName {
            get {
                return ResourceManager.GetString("FormContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email....
        /// </summary>
        public static string FormContactNotify {
            get {
                return ResourceManager.GetString("FormContactNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a message..
        /// </summary>
        public static string FormContactRequiredMessage {
            get {
                return ResourceManager.GetString("FormContactRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name..
        /// </summary>
        public static string FormContactRequiredName {
            get {
                return ResourceManager.GetString("FormContactRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string FormContactSend {
            get {
                return ResourceManager.GetString("FormContactSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully..
        /// </summary>
        public static string FormContactSuccess {
            get {
                return ResourceManager.GetString("FormContactSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am self-taught..
        /// </summary>
        public static string HeaderBio {
            get {
                return ResourceManager.GetString("HeaderBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets talk....
        /// </summary>
        public static string HeaderContact {
            get {
                return ResourceManager.GetString("HeaderContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The future has landed.
        /// </summary>
        public static string HeaderSplash {
            get {
                return ResourceManager.GetString("HeaderSplash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I love riding.
        /// </summary>
        public static string HeaderStory {
            get {
                return ResourceManager.GetString("HeaderStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On to the fun tech stuff..
        /// </summary>
        public static string HeaderTech {
            get {
                return ResourceManager.GetString("HeaderTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        public static string HeaderTechAPI {
            get {
                return ResourceManager.GetString("HeaderTechAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string HeaderTechEvents {
            get {
                return ResourceManager.GetString("HeaderTechEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string HeaderTechUsers {
            get {
                return ResourceManager.GetString("HeaderTechUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        public static string HeaderWelcome {
            get {
                return ResourceManager.GetString("HeaderWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio/Resume.
        /// </summary>
        public static string LinkBio {
            get {
                return ResourceManager.GetString("LinkBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landed MVC.
        /// </summary>
        public static string LogoHome {
            get {
                return ResourceManager.GetString("LogoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Swagger UI.
        /// </summary>
        public static string NavAPI {
            get {
                return ResourceManager.GetString("NavAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Repository.
        /// </summary>
        public static string NavAPIRepo {
            get {
                return ResourceManager.GetString("NavAPIRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Me.
        /// </summary>
        public static string NavContactMe {
            get {
                return ResourceManager.GetString("NavContactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string NavEvents {
            get {
                return ResourceManager.GetString("NavEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVC.
        /// </summary>
        public static string NavMVC {
            get {
                return ResourceManager.GetString("NavMVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NavNext {
            get {
                return ResourceManager.GetString("NavNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Other Projects.
        /// </summary>
        public static string NavOtherProjects {
            get {
                return ResourceManager.GetString("NavOtherProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string NavRepos {
            get {
                return ResourceManager.GetString("NavRepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume/Bio.
        /// </summary>
        public static string NavResume {
            get {
                return ResourceManager.GetString("NavResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple MVC.
        /// </summary>
        public static string NavSimpleMVC {
            get {
                return ResourceManager.GetString("NavSimpleMVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple MVC Repository.
        /// </summary>
        public static string NavSimpleMVCRepo {
            get {
                return ResourceManager.GetString("NavSimpleMVCRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple SignalR.
        /// </summary>
        public static string NavSimpleSignalR {
            get {
                return ResourceManager.GetString("NavSimpleSignalR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple SignalR Repository.
        /// </summary>
        public static string NavSimpleSignalRRepo {
            get {
                return ResourceManager.GetString("NavSimpleSignalRRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Repository.
        /// </summary>
        public static string NavThisRepo {
            get {
                return ResourceManager.GetString("NavThisRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string NavUsers {
            get {
                return ResourceManager.GetString("NavUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Never memorize something that you can look up.&quot; - &lt;strong&gt;Albert Einstein&lt;/strong&gt;.
        /// </summary>
        public static string SubHeaderBio {
            get {
                return ResourceManager.GetString("SubHeaderBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me an email the easy way. This form uses an endpoint in my API to send me an email..
        /// </summary>
        public static string SubHeaderContact {
            get {
                return ResourceManager.GetString("SubHeaderContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, last year I had a severe accident..
        /// </summary>
        public static string SubHeaderStory {
            get {
                return ResourceManager.GetString("SubHeaderStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	I created two tables in my database. Users and Events. They represent a common one-to-many relationship.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	The choice to use Users and Events was completely arbitrary. They are not tied to anything functional. So feel free to add, edit, or delete them without fear.
        ///&lt;/p&gt;.
        /// </summary>
        public static string SubHeaderTech {
            get {
                return ResourceManager.GetString("SubHeaderTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access the API directly using its Swagger UI..
        /// </summary>
        public static string SubHeaderTechAPI {
            get {
                return ResourceManager.GetString("SubHeaderTechAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From here you can access all the events independently of users..
        /// </summary>
        public static string SubHeaderTechEvents {
            get {
                return ResourceManager.GetString("SubHeaderTechEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a normal one-to-many flow. Things would start here..
        /// </summary>
        public static string SubHeaderTechUsers {
            get {
                return ResourceManager.GetString("SubHeaderTechUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to &lt;strong&gt;Landed MVC!&lt;/strong&gt;.
        /// </summary>
        public static string SubHeaderWelcome {
            get {
                return ResourceManager.GetString("SubHeaderWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As an autodidact software developer, I&apos;ve been on a journey that began in childhood and spans two decades of experience in enterprise web software development. My coding journey has traversed a diverse landscape, from BASIC to C#. Beyond writing code, I&apos;m an avid reader, and gamer..
        /// </summary>
        public static string TextBio {
            get {
                return ResourceManager.GetString("TextBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And there are no hoverboards or flying cars.&lt;br /&gt;
        ///Just me and Landed MVC...  &amp;#128514;.
        /// </summary>
        public static string TextSplash {
            get {
                return ResourceManager.GetString("TextSplash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///	I only bring this up because I have been out of work for a year. Mostly due to this accident and the time it has taken to recover.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	This has made me a bit rusty, and that has a lot to do with why these demo projects exist. They serve as both a refresher for my memory and a means to alleviate any concerns employers may have about my abilities.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///	Well enough about me...
        ///&lt;/p&gt;.
        /// </summary>
        public static string TextStory {
            get {
                return ResourceManager.GetString("TextStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This web application was built using .NET 8 MVC and some nice (and free) responsive design work from &lt;a href=&quot;https://html5up.net/landed&quot; target=&quot;_blank&quot;&gt;HTML5 UP&lt;/a&gt;. It looks best on a desktop, but is completely responsive to mobile screen sizes. Most of the credit for this lies in the design, but I&apos;ve added a fair amount of JS and CSS myself..
        /// </summary>
        public static string TextWelcome1 {
            get {
                return ResourceManager.GetString("TextWelcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It leverages a REST API for its backend, which is the same API utilized by my other demo applications. Consequently, modifications made here will seamlessly propagate to those applications, and vice versa. Embracing an API for the backend offers the flexibility to connect various frontends or implement alterations to them autonomously..
        /// </summary>
        public static string TextWelcome2 {
            get {
                return ResourceManager.GetString("TextWelcome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landed MVC.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }
    }
}
